[package]
name = "rune"
version = "0.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>", "Matt Garnett <14004106+lightclient@users.noreply.github.com>"]
edition = "2018"

[dependencies]
wasmi = "0.5.0"
